--- Generated by h-lua(https://github.com/h-lua/h-lua)

SETUP = function()

    -- 调试删迷雾
    cj.FogEnable(not DEBUGGING)
    cj.FogMaskEnable(not DEBUGGING)

    -- 设定玩家
    hplayer.qty_max = 1 -- 最大玩家数
    hplayer.convert_ratio = 1000000 -- 换算比率，100金 -> 1木

    -- 设定玩家
    hplayer.qty_max = 1 -- 最大玩家数
    hplayer.convert_ratio = 1000000 -- 换算比率，100金 -> 1木

    -- 设定敌军
    henemy.set("怪物", nil, { 2 }, false)

end
