-- 附魔系统
CONST_ENCHANT = {
    { value = "physical", label = "物理", color = "d9d9d9" },
    { value = "magic", label = "魔法", color = "4876ff" },
    { value = "fire", label = "火", color = "f45454" },
    { value = "flame", label = "焰", color = "f46b54" },
    { value = "soil", label = "土", color = "dbb745" },
    { value = "rock", label = "岩", color = "947410" },
    { value = "sand", label = "砂", color = "c3a33c" },
    { value = "lava", label = "熔", color = "ab2217" },
    { value = "water", label = "水", color = "85adee" },
    { value = "ice", label = "冰", color = "85f4f4" },
    { value = "storm", label = "岚", color = "6edea4" },
    { value = "wind", label = "风", color = "b6d7a8" },
    { value = "light", label = "光", color = "f9f99c" },
    { value = "dark", label = "暗", color = "696969" },
    { value = "wood", label = "木", color = "7cbd60" },
    { value = "grass", label = "草", color = "8cdd69" },
    { value = "thunder", label = "雷", color = "f0db33" },
    { value = "electric", label = "电", color = "ebe75c" },
    { value = "metal", label = "金", color = "f9f99c" },
    { value = "iron", label = "铁", color = "ccd6ea" },
    { value = "steel", label = "钢", color = "9eaecc" },
    { value = "dragon", label = "龙", color = "7cbd60" },
    { value = "insect", label = "虫", color = "ba55d3" },
    { value = "poison", label = "毒", color = "3cb371" },
    { value = "evil", label = "邪", color = "983e6f" },
    { value = "ghost", label = "鬼", color = "615656" },
    { value = "god", label = "神", color = "ffffff" },
    { value = "holy", label = "圣", color = "efef8f" },
}
