-- 作用目标

CONST_TARGET_LABEL = {
    notself = "别人",
    debris = "残骸",
    alive = "存活",
    ground = "地面",
    terrain = "地形",
    enemies = "敌人",
    enemy = "敌人",
    ancient = "古树",
    mechanical = "机械类",
    structure = "建筑",
    vuln = "可攻击的",
    air = "空中",
    allies = "联盟",
    none = "没有",
    well = "墙",
    bridge = "桥",
    ward = "守卫",
    tree = "树木",
    dead = "死亡",
    player = "玩家单位",
    invu = "无敌",
    item = "物品",
    hero = "英雄",
    friend = "友军",
    organic = "有机生物",
    neutral = "中立",
    decoration = "装饰物",
    sapper = "自爆工兵",
    self = "自己",
    nonancient = "非古树",
    nonhero = "非英雄",
    nonsapper = "非自爆兵",
}