-- 加载YDWE库
cj = require "jass.common"
cg = require "jass.globals"

require "blizzard_c"
require "blizzard_b"
require "echo"

require "lib.id"
require "lib.slk"
require "lib.cache"
require "lib.cmd"
require "lib.dzapi"
require "lib.dzui"
require "lib.japi"
require "lib.time"
require "lib.monitor"
require "lib.is"
require "lib.sound"
require "lib.texture"
require "lib.effect"
require "lib.lightning"
require "lib.weather"
require "lib.env"
require "lib.camera"
require "lib.event"
require "lib.eventDefaultActions"
require "lib.textTag"
require "lib.rect"
require "lib.player"
require "lib.award"
require "lib.unit"
require "lib.enemy"
require "lib.group"
require "lib.hero"
require "lib.skill.index"
require "lib.skill.basic"
require "lib.skill.damage"
require "lib.skill.complex"
require "lib.skill.ring"
require "lib.buff"
require "lib.enchant"
require "lib.attribute.setter"
require "lib.attribute.index"
require "lib.attribute.xtras"
require "lib.item"
require "lib.itemPool"
require "lib.dialog"
require "lib.leaderBoard"
require "lib.multiBoard"
require "lib.quest"
require "lib.shop"

require "lib.initialization"
