--- Generated by h-lua(https://github.com/h-lua/h-lua)

require "h-lua" -- h-lua库
require "scripts.alias" -- h-lua库别称（参考）
require "scripts.setup" -- 游戏准备
require "scripts.eventReaction" -- 事件反应
require "scripts.damaging" -- 伤害流
require "scripts.ui" -- UI

-- h-lua main function 主函数入口
-- The game starts here 游戏从main函数开始运行
function main()

    SETUP()
    UI()

    print("你好，世界！")
    echo("你好，世界！")
    dump({ "你好，世界！" }, "dump")

    hitem.create({
        id = hslk.n2i("物理学圣剑"),
        x = 100,
        y = 0,
    })

    hunit.create({
        whichPlayer = hplayer.players[1],
        id = hslk.n2i("天选勇者"),
        x = 0,
        y = 0,
        isOpenSlot = true,
    })

end